### ISSUE TITLE
A problem occurred evaluating project ':app'

### ISSUE THREAD

**Issue by arstagaev** [aurasphere/blue-pair#24] opened 2021-03-11 06:47 UTC
Hi! 
I have issue, when i first build project:
```
Build file 'C:\Users\ion8\AndroidStudioProjects\blue-pair\app\build.gradle' line: 17

A problem occurred evaluating project ':app'.
> C:\blue-pair\blue-pair-secret.properties (The system cannot find the file specified)
```

I read previous issues and I think I should create some file with some configuration. Where I should destination this file? What I should write in this file? 
<img width="925" alt="okjpok" src="https://user-images.githubusercontent.com/53790451/110747044-cb038e80-824e-11eb-96a1-790c044614c5.png">

**Comment by aurasphere** [comment] 2021-04-11 14:39
Hey @arstagaev this is a duplicate of issue #23. There's a detailed description of the content of the file, which should be placed on the same location written in the error you are getting. As per the values to be inserted, they are related to the ads configuration, so you will have to register and follow the AdMob tutorials if you want to run a production build

**Closed as completed by aurasphere** 2021-04-11 14:39 UTC
