### ISSUE TITLE
Bug on Blue-Pair App: Bluetooth fails to pair device again after disconnected from other device

### ISSUE THREAD

**Issue by gutzygwin** [aurasphere/blue-pair#17] opened 2018-03-04 04:23 UTC
#### Expected behavior
Blue pair is an open source  andriod app which is meant for pairing and finding nearby Bluetooth devices with the aid of an in-built Bluetooth accessory on the mobile device. Bluetooth is expected to connect and pair Bluetooth devices upon use of Bluetooth conveniently. 

#### Actual behavior
Upon pairing the Bluetooth using blue pair application, and then disconnecting the connection (or unpairing the devices) from other devices, blue pair fails to pair again with that particular Bluetooth devices and as such will keep showing this message "bluetooth device has already been paired" whereas it hasn't been paired and other devices remain unconnected. 

![Screenshot_20180304-002456.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520120372/ybuoxikutryyk5uprvks.png)

#### How to reproduce
* Download the Blue pair from Google playstore. 
* open the app and  search for Bluetooth device and pair with another mobile phone using the Bluetooth settings on the other device.
* Pair both devices. 
* Unpair from the other device from Bluetooth settings.
* Reload the "mobile device with blue pair app" and try pairing again with the app. 
* App fails to pair again and shows the mesaage "Bluetooth device has already been paired" , whereas the device isn't pairing. 

--------------------------------------------------------

* Browser: Google Playstore/Blue-Pair
* Operating system: Andriod 7.0 . Infinix Note 4.

#### Recording Of The Bug

https://youtu.be/4ZXn33MQGqQ
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-blue-pair-app-bluetooth-fails-to-pair-device-again-after-disconnected-from-other-device">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by aurasphere** [comment] 2018-03-04 14:58
Hey @gutzygwin , 

thank you very much for taking your time to open this very detailed and well-written issue.

I've looked into this and reproduced the steps you wrote but I haven't been able to find any bugs in this workflow. I've also noticed that the video you attached is a little bit different from the steps you enumerated. So, let me address both cases:

## Youtube Video: Pairing two devices and then restarting Bluetooth
In this case, the devices are supposed to be still paired after turning the Bluetooth back on. Please be aware that Bluetooth pairing and connection are not the same.
 - **Pairing**: required only once until the devices are unpaired.
 - **Connection**: required each time a Bluetooth device turn off and on again or after the connection is lost (through an explicit disconnection request for example)

This app performs only the former operation since the latter is usually tied to a specific service one device exposes and this is out of Blue Pair's scope.

## Steps on "How to reproduce" section
I've been following this steps but I didn't have any luck on reproducing the issue. Here's what I've done:
 1. Pair a device from Blue Pair
 2. Unpair the same device from Android's settings
 3. Pair again the device from Blue Pair

[Here's a video recording of this so you can tell me if I missed something.](https://github.com/aurasphere/blue-pair/files/1778604/device-2018-03-04-153345.zip)

Also, I find that some devices (like my computer) automatically fail the second pair attempt if you perform the unpairing from only one side (in my case, I've unpaired the PC from the Android device but I couldn't connect again until I've also removed the Android device from the PC). Please let me know if this was also your case.

Feel free to reply or close the issue. Thank you again from your report and your time.

**Closed** 2018-08-26 09:32 UTC
